var OA_output = new Array(); 
OA_output['Sidebar 1'] = '';

OA_output['Sidebar 2'] = '';

OA_output['Sidebar 3'] = '';

OA_output['Medium Rectangle'] = '';
OA_output['Medium Rectangle'] += "<"+"iframe src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080748&PluID=0&w=300&h=250&ord=$$CacheBustingToken$$&wm=transparent&ifrm=2&ucm=true\" width=300 height=250 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0  scrolling=no bordercolor=\"#000000\">\n";
OA_output['Medium Rectangle'] += "<"+"/iframe><"+"div id=\'beacon_c6fd21b6f8\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7700&amp;campaignid=252&amp;zoneid=22&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;cb=c6fd21b6f8\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Homepage prem Ad'] = '';
OA_output['Homepage prem Ad'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7395__zoneid=25__OXLCA=1__cb=48f33ecdc1__oadest=http%3A%2F%2Fwww.godaddy.com%2Fhosting%2Fwordpress-hosting.aspx%3Fisc%3Dsmag1wphp%26ci%3D88548%26utm_campaign%3D1_managed_wp%26utm_source%3Dsmashing_magazine%26utm_medium%3DOther%252BOnline%26utm_content%3Dsmag1wphp%26cvosrc%3Ddisplay.smashingmagazine.bca-1160_smashing_hosting_banners_540x150\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=bca-1160_smashing_hosting_banners_540x150-1_copy.jpg&contenttype=jpeg\' width=\'540\' height=\'150\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_48f33ecdc1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7395&amp;campaignid=2785&amp;zoneid=25&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=48f33ecdc1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"img src=\"http://godaddy.sp1.convertro.com/view/vt/v1/godaddy/1/cvo.gif?cvosrc=display.smashingmagazine.bca-1160_smashing_hosting_banners_540x150\" alt=\"\"/>\n";
OA_output['Sidebar Special 1'] = '';

OA_output['Sidebar Special 2'] = '';

OA_output['Textad'] = '';
OA_output['Textad'] += "<"+"div id=\"textad\"><"+"script type=\'text/javascript\'><"+"!--//<"+"![CDATA[\n";
OA_output['Textad'] += "document.MAX_ct0 =\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=568bd9e8c4__oadest=\';\n";
OA_output['Textad'] += "var m3_u = (location.protocol==\'https:\'?\'https://auslieferung.commindo-media-ressourcen.de/www/delivery/ajs.php\':\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ajs.php\');\n";
OA_output['Textad'] += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OA_output['Textad'] += "if (!document.MAX_used) document.MAX_used = \',\';\n";
OA_output['Textad'] += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OA_output['Textad'] += "document.write (\"?zoneid=94\");\n";
OA_output['Textad'] += "document.write (\'&amp;cb=\' + m3_r);\n";
OA_output['Textad'] += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OA_output['Textad'] += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OA_output['Textad'] += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OA_output['Textad'] += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OA_output['Textad'] += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OA_output['Textad'] += "if ((typeof(document.MAX_ct0) != \'undefined\') && (document.MAX_ct0.substring(0,4) == \'http\')) {\n";
OA_output['Textad'] += "document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));\n";
OA_output['Textad'] += "}\n";
OA_output['Textad'] += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OA_output['Textad'] += "document.write (\"\'><"+"\\/scr\"+\"ipt>\");\n";
OA_output['Textad'] += "//]]>--><"+"/script><"+"noscript><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=568bd9e8c4__oadest=http%3A%2F%2Fauslieferung.commindo-media-ressourcen.de%2Fwww%2Fdelivery%2Fck.php%3Fn%3Daf102b35%26amp%3Bcb%3D568bd9e8c4\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/avw.php?zoneid=94&amp;cb=568bd9e8c4&amp;n=af102b35&amp;ct0=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=568bd9e8c4__oadest=\' border=\'0\' alt=\'\' /><"+"/a><"+"/noscript><"+"div id=\'beacon_568bd9e8c4\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6259&amp;campaignid=1018&amp;zoneid=68&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;cb=568bd9e8c4\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['Comment Sponsor'] = '';
OA_output['Comment Sponsor'] += "<"+"style type=\"text/css\">\n";
OA_output['Comment Sponsor'] += "div div.singlepost.advertisement span.declare {\n";
OA_output['Comment Sponsor'] += "display: none;\n";
OA_output['Comment Sponsor'] += "}\n";
OA_output['Comment Sponsor'] += "<"+"/style><"+"style type=\"text/css\">.comment-job-board { margin: 2em 6% 2em 0; background: #FEFED3; padding: 1.25em 1em;	overflow: hidden; font: 1.2em/1.4em \"Skolar Bold\", Georgia, serif; }.comment-job-board a {display: block;color: #000;}.comment-job-board a span {padding-top:0.75em;display: block;font: 0.8em/1.4em \"Proxima Nova Regular\", Arial, sans-serif;}.comment-job-board a:focus, .comment-job-board a:active {background-color: transparent;}.comment-job-board img {float: right;margin: 0 0 0em 1em;}<"+"/style>\n";
OA_output['Comment Sponsor'] += "<"+"div class=\"comment-job-board\"><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4551__zoneid=26__OXLCA=1__cb=e3d0bf081f__oadest=http%3A%2F%2Fjobs.smashingmagazine.com%2F%3Futm_source%3Dsm%26utm_medium%3Dtextad%26utm_campaign%3Dinternal\" target=\"_self\"><"+"img src=\"http://www.smashingmagazine.com/wp-content/uploads/2012/01/job-board-transparent.gif\" style=\"border-radius: 5px; border: 1px solid rgba(0,0,0,0.05); padding: 7px; background-color: #fff; max-width: 95px !important;\" width=\"95\" />Post your job listing in our Job Board!<"+"span>If you\'re looking for a job or have a job opening to announce, post it in our job board and get noticed by professionals and well-respected companies. <"+"b style=\"text-decoration: underline;font-family: Proxima Nova Bold, Proxima Nova, Arial\">Submit a job listing<"+"/b>, and good luck!<"+"/span><"+"/a><"+"/div><"+"div id=\'beacon_e3d0bf081f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4551&amp;campaignid=1593&amp;zoneid=26&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;cb=e3d0bf081f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 1'] = '';

OA_output['VIS 2'] = '';

OA_output['VIS 3'] = '';

OA_output['VIS 4'] = '';

OA_output['VIS 5'] = '';

OA_output['VIS 6'] = '';

OA_output['VIS 7'] = '';

OA_output['VIS 8'] = '';

OA_output['VIS 9'] = '';

OA_output['VIS 10'] = '';

OA_output['spnsr ROS 1'] = '';
OA_output['spnsr ROS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7502__zoneid=24__OXLCA=1__cb=3264e4cb46__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai-1b_2.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7502__zoneid=24__OXLCA=1__cb=3264e4cb46__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_3264e4cb46\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7502&amp;campaignid=2815&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=3264e4cb46\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 2'] = '';
OA_output['spnsr ROS 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6928__zoneid=24__OXLCA=1__cb=7f0853e74d__oadest=https%3A%2F%2Fw3-markup.com%2Forder%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dnew\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200-125_4.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'PSD to HTML Services\' title=\'PSD to HTML Services\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6928__zoneid=24__OXLCA=1__cb=7f0853e74d__oadest=https%3A%2F%2Fw3-markup.com%2Forder%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dnew\' target=\'_blank\'>PSD to HTML Services<"+"/a><"+"div id=\'beacon_7f0853e74d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6928&amp;campaignid=2394&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=7f0853e74d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 3'] = '';
OA_output['spnsr ROS 3'] += "<"+"iframe src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080755&PluID=0&w=200&h=125&ord=$$CacheBustingToken$$&wm=transparent&ifrm=2&ucm=true\" width=200 height=125 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0  scrolling=no bordercolor=\"#000000\">\n";
OA_output['spnsr ROS 3'] += "<"+"/iframe>\n";
OA_output['spnsr ROS 3'] += "<"+"br><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7697__zoneid=24__OXLCA=1__cb=793e4b1223__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D6429\" target=\"_blank\">Create free stunning sites!<"+"/a><"+"div id=\'beacon_793e4b1223\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7697&amp;campaignid=130&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;cb=793e4b1223\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 4'] = '';
OA_output['spnsr ROS 4'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7835__zoneid=24__OXLCA=1__cb=1697e310de__oadest=http%3A%2F%2Fwww.invisionapp.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3D200x125%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_(1).jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Get Started -- Free Forever\' title=\'Get Started -- Free Forever\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7835__zoneid=24__OXLCA=1__cb=1697e310de__oadest=http%3A%2F%2Fwww.invisionapp.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3D200x125%26utm_campaign%3Dsmashing\' target=\'_blank\'>Get Started -- Free Forever<"+"/a><"+"div id=\'beacon_1697e310de\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7835&amp;campaignid=2874&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=1697e310de\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 5'] = '';
OA_output['spnsr ROS 5'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7486__zoneid=24__OXLCA=1__cb=92858925e5__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DReinvent%26utm_campaign%3DKent%25202014\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=kent_250x125_banner3_uxd_reinvent.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Kent State Online\' title=\'Kent State Online\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7486__zoneid=24__OXLCA=1__cb=92858925e5__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DReinvent%26utm_campaign%3DKent%25202014\' target=\'_blank\'>Kent State Online<"+"/a><"+"div id=\'beacon_92858925e5\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7486&amp;campaignid=2807&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=92858925e5\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 6'] = '';
OA_output['spnsr ROS 6'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7545__zoneid=24__OXLCA=1__cb=b444169210__oadest=http%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vectors%3FSM%3D2\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=vsfree-2-smas-200x125_12.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Free + Royalty Free Vector Art\' title=\'Free + Royalty Free Vector Art\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7545__zoneid=24__OXLCA=1__cb=b444169210__oadest=http%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vectors%3FSM%3D2\' target=\'_blank\'>Free + Royalty Free Vector Art<"+"/a><"+"div id=\'beacon_b444169210\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7545&amp;campaignid=2834&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=b444169210\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 7'] = '';
OA_output['spnsr ROS 7'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7525__zoneid=24__OXLCA=1__cb=1a4f878a54__oadest=http%3A%2F%2Fbit.ly%2F1lcLE6Q\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=sm-june_200x125.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Leading Web Design Books​\' title=\'Leading Web Design Books​\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7525__zoneid=24__OXLCA=1__cb=1a4f878a54__oadest=http%3A%2F%2Fbit.ly%2F1lcLE6Q\' target=\'_blank\'>Leading Web Design Books​<"+"/a><"+"div id=\'beacon_1a4f878a54\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7525&amp;campaignid=2738&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=1a4f878a54\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 8'] = '';
OA_output['spnsr ROS 8'] += "<"+"iframe src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080749&PluID=0&w=200&h=125&ord=$$CacheBustingToken$$&wm=transparent&ifrm=2&ucm=true\" width=200 height=125 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0  scrolling=no bordercolor=\"#000000\">\n";
OA_output['spnsr ROS 8'] += "<"+"/iframe>\n";
OA_output['spnsr ROS 8'] += "<"+"br><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7698__zoneid=24__OXLCA=1__cb=dd3288b4e6__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D6429\" target=\"_blank\">Create free stunning sites!<"+"/a><"+"div id=\'beacon_dd3288b4e6\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7698&amp;campaignid=250&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;cb=dd3288b4e6\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 9'] = '';
OA_output['spnsr ROS 9'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7701__zoneid=24__OXLCA=1__cb=5bb6a30305__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_168.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Form Builder\' title=\'Online Form Builder\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7701__zoneid=24__OXLCA=1__cb=5bb6a30305__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'>Online Form Builder<"+"/a><"+"div id=\'beacon_5bb6a30305\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7701&amp;campaignid=2847&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=5bb6a30305\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 10'] = '';
OA_output['spnsr ROS 10'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7552__zoneid=24__OXLCA=1__cb=5f872606c5__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_9.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7552__zoneid=24__OXLCA=1__cb=5f872606c5__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_5f872606c5\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7552&amp;campaignid=2838&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=5f872606c5\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 11'] = '';
OA_output['spnsr ROS 11'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7656__zoneid=24__OXLCA=1__cb=aed5405f91__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DThink%2520Forward%26utm_campaign%3DKent%25202014\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_28.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Kent State Online\' title=\'Kent State Online\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7656__zoneid=24__OXLCA=1__cb=aed5405f91__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DThink%2520Forward%26utm_campaign%3DKent%25202014\' target=\'_blank\'>Kent State Online<"+"/a><"+"div id=\'beacon_aed5405f91\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7656&amp;campaignid=2844&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=aed5405f91\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 12'] = '';
OA_output['spnsr ROS 12'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7494__zoneid=24__OXLCA=1__cb=ba148b8ec0__oadest=http%3A%2F%2Ftheme.co%2Fx%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=x-smashing_2.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'30+ Demos - See It Live!\' title=\'30+ Demos - See It Live!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7494__zoneid=24__OXLCA=1__cb=ba148b8ec0__oadest=http%3A%2F%2Ftheme.co%2Fx%2F\' target=\'_blank\'>30+ Demos - See It Live!<"+"/a><"+"div id=\'beacon_ba148b8ec0\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7494&amp;campaignid=2813&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=ba148b8ec0\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 13'] = '';
OA_output['spnsr ROS 13'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7673__zoneid=24__OXLCA=1__cb=a8668c6cd6__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DThink%2520Forward%26utm_campaign%3DKent%25202014\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_38.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Kent State Online\' title=\'Kent State Online\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7673__zoneid=24__OXLCA=1__cb=a8668c6cd6__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DThink%2520Forward%26utm_campaign%3DKent%25202014\' target=\'_blank\'>Kent State Online<"+"/a><"+"div id=\'beacon_a8668c6cd6\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7673&amp;campaignid=2845&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=a8668c6cd6\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 14'] = '';
OA_output['spnsr ROS 14'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7704__zoneid=24__OXLCA=1__cb=0364372a7e__oadest=http%3A%2F%2Fwww.themevilla.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125-smashingmagazine_5.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Best Web Templates\' title=\'Best Web Templates\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7704__zoneid=24__OXLCA=1__cb=0364372a7e__oadest=http%3A%2F%2Fwww.themevilla.com\' target=\'_blank\'>Best Web Templates<"+"/a><"+"div id=\'beacon_0364372a7e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7704&amp;campaignid=2849&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=0364372a7e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 15'] = '';
OA_output['spnsr ROS 15'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7680__zoneid=24__OXLCA=1__cb=353cfb0cde__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_42.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7680__zoneid=24__OXLCA=1__cb=353cfb0cde__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_353cfb0cde\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7680&amp;campaignid=2846&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=353cfb0cde\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 16'] = '';

OA_output['spnsr ROS 17'] = '';
OA_output['spnsr ROS 17'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7707__zoneid=24__OXLCA=1__cb=6fb49de4cc__oadest=http%3A%2F%2Fwww.contractmint.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=get_freelance_contracts.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Get Freelancer Contracts\' title=\'Get Freelancer Contracts\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7707__zoneid=24__OXLCA=1__cb=6fb49de4cc__oadest=http%3A%2F%2Fwww.contractmint.com\' target=\'_blank\'>Get Freelancer Contracts<"+"/a><"+"div id=\'beacon_6fb49de4cc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7707&amp;campaignid=2851&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=6fb49de4cc\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 18'] = '';

OA_output['Sponsor XXL 1'] = '';
OA_output['Sponsor XXL 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7184__zoneid=77__OXLCA=1__cb=4150909719__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Fsandbox%2Fdrag-and-drop-responsive-grid%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmmag_grid_green_banner\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=responsive-grid-smashing_magazine_2.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'Drag &amp; Drop Responsive Grid\' title=\'Drag &amp; Drop Responsive Grid\' border=\'0\' /><"+"/a><"+"div id=\'beacon_4150909719\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7184&amp;campaignid=2687&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=4150909719\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 2'] = '';
OA_output['Sponsor XXL 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7391__zoneid=77__OXLCA=1__cb=ea2ec9a961__oadest=http%3A%2F%2Fwww.godaddy.com%2Fhosting%2Fwordpress-hosting.aspx%3Fisc%3Dsmag1wpsb%26ci%3D88548%26utm_campaign%3D1_managed_wp%26utm_source%3Dsmashing_magazine%26utm_medium%3DOther%252BOnline%26utm_content%3Dsmag1wpsb%26cvosrc%3Ddisplay.smashingmagazine.bca-1160_smashing_hosting_banners_410x125\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=bca-1160_smashing_hosting_banners_410x125_copy.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_ea2ec9a961\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7391&amp;campaignid=2781&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=ea2ec9a961\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"img src=\"http://godaddy.sp1.convertro.com/view/vt/v1/godaddy/1/cvo.gif?cvosrc=display.smashingmagazine.bca-1160_smashing_hosting_banners_410x125\" alt=\"\"/>\n";
OA_output['Sponsor XXL 3'] = '';
OA_output['Sponsor XXL 3'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7507__zoneid=77__OXLCA=1__cb=d5be945bda__oadest=http%3A%2F%2Fsquarespace.com%2F%3Fchannel%3Ddisplay%26subchannel%3Dsmashing%26source%3Dus%26campaign%3Ddisplay_ad%26subcampaign%3Dtechnology\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=405x125-4_(3).jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_d5be945bda\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7507&amp;campaignid=2818&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F02%2F08%2Fcolor-theory-for-designer-part-3-creating-your-own-color-palettes%2F&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=d5be945bda\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 4'] = '';

OA_output['Sponsor XXL 5'] = '';

