var OA_output = new Array(); 
OA_output['Sidebar 1'] = '';

OA_output['Sidebar 2'] = '';

OA_output['Sidebar 3'] = '';

OA_output['Medium Rectangle'] = '';
OA_output['Medium Rectangle'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7526__zoneid=22__OXLCA=1__cb=a2a011130f__oadest=http%3A%2F%2Fbit.ly%2F1qwsKQA\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=sm-june_300x250_2.gif&contenttype=gif\' width=\'300\' height=\'250\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_a2a011130f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7526&amp;campaignid=2739&amp;zoneid=22&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=a2a011130f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Homepage prem Ad'] = '';

OA_output['Sidebar Special 1'] = '';

OA_output['Sidebar Special 2'] = '';

OA_output['Textad'] = '';
OA_output['Textad'] += "<"+"div id=\"textad\"><"+"script type=\'text/javascript\'><"+"!--//<"+"![CDATA[\n";
OA_output['Textad'] += "document.MAX_ct0 =\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=3050f31c78__oadest=\';\n";
OA_output['Textad'] += "var m3_u = (location.protocol==\'https:\'?\'https://auslieferung.commindo-media-ressourcen.de/www/delivery/ajs.php\':\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ajs.php\');\n";
OA_output['Textad'] += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OA_output['Textad'] += "if (!document.MAX_used) document.MAX_used = \',\';\n";
OA_output['Textad'] += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OA_output['Textad'] += "document.write (\"?zoneid=94\");\n";
OA_output['Textad'] += "document.write (\'&amp;cb=\' + m3_r);\n";
OA_output['Textad'] += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OA_output['Textad'] += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OA_output['Textad'] += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OA_output['Textad'] += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OA_output['Textad'] += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OA_output['Textad'] += "if ((typeof(document.MAX_ct0) != \'undefined\') && (document.MAX_ct0.substring(0,4) == \'http\')) {\n";
OA_output['Textad'] += "document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));\n";
OA_output['Textad'] += "}\n";
OA_output['Textad'] += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OA_output['Textad'] += "document.write (\"\'><"+"\\/scr\"+\"ipt>\");\n";
OA_output['Textad'] += "//]]>--><"+"/script><"+"noscript><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=3050f31c78__oadest=http%3A%2F%2Fauslieferung.commindo-media-ressourcen.de%2Fwww%2Fdelivery%2Fck.php%3Fn%3Daf102b35%26amp%3Bcb%3D3050f31c78\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/avw.php?zoneid=94&amp;cb=3050f31c78&amp;n=af102b35&amp;ct0=http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6259__zoneid=68__OXLCA=1__cb=3050f31c78__oadest=\' border=\'0\' alt=\'\' /><"+"/a><"+"/noscript><"+"div id=\'beacon_3050f31c78\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6259&amp;campaignid=1018&amp;zoneid=68&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=3050f31c78\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['Comment Sponsor'] = '';
OA_output['Comment Sponsor'] += "<"+"style type=\"text/css\">\n";
OA_output['Comment Sponsor'] += "div div.singlepost.advertisement span.declare {\n";
OA_output['Comment Sponsor'] += "display: none;\n";
OA_output['Comment Sponsor'] += "}\n";
OA_output['Comment Sponsor'] += "<"+"/style><"+"style type=\"text/css\">.comment-job-board { margin: 2em 6% 2em 0; background: #FEFED3; padding: 1.25em 1em;	overflow: hidden; font: 1.2em/1.4em \"Skolar Bold\", Georgia, serif; }.comment-job-board a {display: block;color: #000;}.comment-job-board a span {padding-top:0.75em;display: block;font: 0.8em/1.4em \"Proxima Nova Regular\", Arial, sans-serif;}.comment-job-board a:focus, .comment-job-board a:active {background-color: transparent;}.comment-job-board img {float: right;margin: 0 0 0em 1em;}<"+"/style>\n";
OA_output['Comment Sponsor'] += "<"+"div class=\"comment-job-board\"><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=4551__zoneid=26__OXLCA=1__cb=f9dbb6ee9c__oadest=http%3A%2F%2Fjobs.smashingmagazine.com%2F%3Futm_source%3Dsm%26utm_medium%3Dtextad%26utm_campaign%3Dinternal\" target=\"_self\"><"+"img src=\"http://www.smashingmagazine.com/wp-content/uploads/2012/01/job-board-transparent.gif\" style=\"border-radius: 5px; border: 1px solid rgba(0,0,0,0.05); padding: 7px; background-color: #fff; max-width: 95px !important;\" width=\"95\" />Post your job listing in our Job Board!<"+"span>If you\'re looking for a job or have a job opening to announce, post it in our job board and get noticed by professionals and well-respected companies. <"+"b style=\"text-decoration: underline;font-family: Proxima Nova Bold, Proxima Nova, Arial\">Submit a job listing<"+"/b>, and good luck!<"+"/span><"+"/a><"+"/div><"+"div id=\'beacon_f9dbb6ee9c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=4551&amp;campaignid=1593&amp;zoneid=26&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=f9dbb6ee9c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['VIS 1'] = '';

OA_output['VIS 2'] = '';

OA_output['VIS 3'] = '';

OA_output['VIS 4'] = '';

OA_output['VIS 5'] = '';

OA_output['VIS 6'] = '';

OA_output['VIS 7'] = '';

OA_output['VIS 8'] = '';

OA_output['VIS 9'] = '';

OA_output['VIS 10'] = '';

OA_output['spnsr ROS 1'] = '';
OA_output['spnsr ROS 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7501__zoneid=24__OXLCA=1__cb=b585832fd3__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_8.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7501__zoneid=24__OXLCA=1__cb=b585832fd3__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_b585832fd3\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7501&amp;campaignid=2815&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=b585832fd3\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 2'] = '';
OA_output['spnsr ROS 2'] += "<"+"iframe src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080755&PluID=0&w=200&h=125&ord=$$CacheBustingToken$$&wm=transparent&ifrm=2&ucm=true\" width=200 height=125 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0  scrolling=no bordercolor=\"#000000\">\n";
OA_output['spnsr ROS 2'] += "<"+"/iframe>\n";
OA_output['spnsr ROS 2'] += "<"+"br><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7697__zoneid=24__OXLCA=1__cb=95ac1d9b1d__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D6429\" target=\"_blank\">Create free stunning sites!<"+"/a><"+"div id=\'beacon_95ac1d9b1d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7697&amp;campaignid=130&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=95ac1d9b1d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 3'] = '';
OA_output['spnsr ROS 3'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6693__zoneid=24__OXLCA=1__cb=52c4f8bb4e__oadest=https%3A%2F%2Fwww.psd2html.com%2Forder-now.html%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dresponsive\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_29.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'PSD2HTML.com\' title=\'PSD2HTML.com\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=6693__zoneid=24__OXLCA=1__cb=52c4f8bb4e__oadest=https%3A%2F%2Fwww.psd2html.com%2Forder-now.html%3Futm_source%3Dsmashingmagazine.com%26utm_medium%3Dbanner%26utm_campaign%3Dresponsive\' target=\'_blank\'>PSD2HTML.com<"+"/a><"+"div id=\'beacon_52c4f8bb4e\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=6693&amp;campaignid=2394&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=52c4f8bb4e\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 4'] = '';
OA_output['spnsr ROS 4'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7486__zoneid=24__OXLCA=1__cb=57dd78307c__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DReinvent%26utm_campaign%3DKent%25202014\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=kent_250x125_banner3_uxd_reinvent.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Kent State Online\' title=\'Kent State Online\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7486__zoneid=24__OXLCA=1__cb=57dd78307c__oadest=http%3A%2F%2Fonlinedegrees.kent.edu%2Fprograms-courses%2Fgraduate%2Fuser-experience-design%2F%3Futm_source%3DSmashing%26utm_medium%3DOnline%2520Media%26utm_content%3DReinvent%26utm_campaign%3DKent%25202014\' target=\'_blank\'>Kent State Online<"+"/a><"+"div id=\'beacon_57dd78307c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7486&amp;campaignid=2807&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=57dd78307c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 5'] = '';
OA_output['spnsr ROS 5'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7835__zoneid=24__OXLCA=1__cb=71d45b9caf__oadest=http%3A%2F%2Fwww.invisionapp.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3D200x125%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125_(1).jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Get Started -- Free Forever\' title=\'Get Started -- Free Forever\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7835__zoneid=24__OXLCA=1__cb=71d45b9caf__oadest=http%3A%2F%2Fwww.invisionapp.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3D200x125%26utm_campaign%3Dsmashing\' target=\'_blank\'>Get Started -- Free Forever<"+"/a><"+"div id=\'beacon_71d45b9caf\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7835&amp;campaignid=2874&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=71d45b9caf\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 6'] = '';
OA_output['spnsr ROS 6'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7525__zoneid=24__OXLCA=1__cb=ff72f74854__oadest=http%3A%2F%2Fbit.ly%2F1lcLE6Q\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=sm-june_200x125.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Leading Web Design Books​\' title=\'Leading Web Design Books​\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7525__zoneid=24__OXLCA=1__cb=ff72f74854__oadest=http%3A%2F%2Fbit.ly%2F1lcLE6Q\' target=\'_blank\'>Leading Web Design Books​<"+"/a><"+"div id=\'beacon_ff72f74854\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7525&amp;campaignid=2738&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=ff72f74854\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 7'] = '';
OA_output['spnsr ROS 7'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7545__zoneid=24__OXLCA=1__cb=7c4a5cc5e1__oadest=http%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vectors%3FSM%3D2\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=vsfree-2-smas-200x125_12.gif&contenttype=gif\' width=\'200\' height=\'125\' alt=\'Free + Royalty Free Vector Art\' title=\'Free + Royalty Free Vector Art\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7545__zoneid=24__OXLCA=1__cb=7c4a5cc5e1__oadest=http%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vectors%3FSM%3D2\' target=\'_blank\'>Free + Royalty Free Vector Art<"+"/a><"+"div id=\'beacon_7c4a5cc5e1\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7545&amp;campaignid=2834&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=7c4a5cc5e1\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 8'] = '';
OA_output['spnsr ROS 8'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7701__zoneid=24__OXLCA=1__cb=57cc8a47fa__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_168.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Form Builder\' title=\'Online Form Builder\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7701__zoneid=24__OXLCA=1__cb=57cc8a47fa__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'>Online Form Builder<"+"/a><"+"div id=\'beacon_57cc8a47fa\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7701&amp;campaignid=2847&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=57cc8a47fa\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 9'] = '';
OA_output['spnsr ROS 9'] += "<"+"iframe src=\"http://bs.serving-sys.com/BurstingPipe/adServer.bs?cn=rsb&c=28&pli=6080749&PluID=0&w=200&h=125&ord=$$CacheBustingToken$$&wm=transparent&ifrm=2&ucm=true\" width=200 height=125 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0  scrolling=no bordercolor=\"#000000\">\n";
OA_output['spnsr ROS 9'] += "<"+"/iframe>\n";
OA_output['spnsr ROS 9'] += "<"+"br><"+"a href=\"http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7698__zoneid=24__OXLCA=1__cb=bb9980ef63__oadest=http%3A%2F%2Fbs.serving-sys.com%2FBurstingPipe%2FadServer.bs%3Fcn%3Dbrd%26FlightID%3D6080749%26Page%3D%26PluID%3D0%26Pos%3D6429\" target=\"_blank\">Create free stunning sites!<"+"/a><"+"div id=\'beacon_bb9980ef63\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7698&amp;campaignid=250&amp;zoneid=24&amp;loc=1&amp;referer=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;cb=bb9980ef63\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 10'] = '';
OA_output['spnsr ROS 10'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7676__zoneid=24__OXLCA=1__cb=c35b641aef__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_165.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Form Builder\' title=\'Online Form Builder\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7676__zoneid=24__OXLCA=1__cb=c35b641aef__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'>Online Form Builder<"+"/a><"+"div id=\'beacon_c35b641aef\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7676&amp;campaignid=2846&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=c35b641aef\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 11'] = '';
OA_output['spnsr ROS 11'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7704__zoneid=24__OXLCA=1__cb=89f39ef704__oadest=http%3A%2F%2Fwww.themevilla.com\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=200x125-smashingmagazine_5.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Best Web Templates\' title=\'Best Web Templates\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7704__zoneid=24__OXLCA=1__cb=89f39ef704__oadest=http%3A%2F%2Fwww.themevilla.com\' target=\'_blank\'>Best Web Templates<"+"/a><"+"div id=\'beacon_89f39ef704\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7704&amp;campaignid=2849&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=89f39ef704\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 12'] = '';
OA_output['spnsr ROS 12'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7659__zoneid=24__OXLCA=1__cb=2606b37625__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_161.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Form Builder\' title=\'Online Form Builder\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7659__zoneid=24__OXLCA=1__cb=2606b37625__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'>Online Form Builder<"+"/a><"+"div id=\'beacon_2606b37625\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7659&amp;campaignid=2845&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=2606b37625\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 13'] = '';
OA_output['spnsr ROS 13'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7643__zoneid=24__OXLCA=1__cb=15f6bdefbe__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_19.jpg&contenttype=jpeg\' width=\'200\' height=\'125\' alt=\'Online Project Management\' title=\'Online Project Management\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7643__zoneid=24__OXLCA=1__cb=15f6bdefbe__oadest=https%3A%2F%2Fwww.zoho.com%2Fprojects%2F%3Futm_source%3Dsmashing_magazine%2F\' target=\'_blank\'>Online Project Management<"+"/a><"+"div id=\'beacon_15f6bdefbe\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7643&amp;campaignid=2844&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=15f6bdefbe\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 14'] = '';
OA_output['spnsr ROS 14'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7551__zoneid=24__OXLCA=1__cb=8daec97117__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=ai_154.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'Online Form Builder\' title=\'Online Form Builder\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7551__zoneid=24__OXLCA=1__cb=8daec97117__oadest=http%3A%2F%2Fwww.jotform.com%2F%3Futm_source%3Dsmashing%26utm_medium%3Dbanner%26utm_content%3Dlogo%26utm_campaign%3Dsmashing\' target=\'_blank\'>Online Form Builder<"+"/a><"+"div id=\'beacon_8daec97117\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7551&amp;campaignid=2838&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=8daec97117\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 15'] = '';

OA_output['spnsr ROS 16'] = '';

OA_output['spnsr ROS 17'] = '';
OA_output['spnsr ROS 17'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7494__zoneid=24__OXLCA=1__cb=b478bedd99__oadest=http%3A%2F%2Ftheme.co%2Fx%2F\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=x-smashing_2.png&contenttype=png\' width=\'200\' height=\'125\' alt=\'30+ Demos - See It Live!\' title=\'30+ Demos - See It Live!\' border=\'0\' /><"+"/a><"+"br /><"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7494__zoneid=24__OXLCA=1__cb=b478bedd99__oadest=http%3A%2F%2Ftheme.co%2Fx%2F\' target=\'_blank\'>30+ Demos - See It Live!<"+"/a><"+"div id=\'beacon_b478bedd99\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7494&amp;campaignid=2813&amp;zoneid=24&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=b478bedd99\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['spnsr ROS 18'] = '';

OA_output['Sponsor XXL 1'] = '';
OA_output['Sponsor XXL 1'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7184__zoneid=77__OXLCA=1__cb=df43cd7a02__oadest=http%3A%2F%2Fwww.sitefinity.com%2Fcampaigns%2Fsandbox%2Fdrag-and-drop-responsive-grid%3Futm_source%3Dsmashing-magazine%26utm_medium%3Dbanner%26utm_campaign%3Dsmmag_grid_green_banner\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=responsive-grid-smashing_magazine_2.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'Drag &amp; Drop Responsive Grid\' title=\'Drag &amp; Drop Responsive Grid\' border=\'0\' /><"+"/a><"+"div id=\'beacon_df43cd7a02\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7184&amp;campaignid=2687&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=df43cd7a02\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 2'] = '';
OA_output['Sponsor XXL 2'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7391__zoneid=77__OXLCA=1__cb=3ea57508dc__oadest=http%3A%2F%2Fwww.godaddy.com%2Fhosting%2Fwordpress-hosting.aspx%3Fisc%3Dsmag1wpsb%26ci%3D88548%26utm_campaign%3D1_managed_wp%26utm_source%3Dsmashing_magazine%26utm_medium%3DOther%252BOnline%26utm_content%3Dsmag1wpsb%26cvosrc%3Ddisplay.smashingmagazine.bca-1160_smashing_hosting_banners_410x125\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=bca-1160_smashing_hosting_banners_410x125_copy.jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_3ea57508dc\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7391&amp;campaignid=2781&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=3ea57508dc\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"img src=\"http://godaddy.sp1.convertro.com/view/vt/v1/godaddy/1/cvo.gif?cvosrc=display.smashingmagazine.bca-1160_smashing_hosting_banners_410x125\" alt=\"\"/>\n";
OA_output['Sponsor XXL 3'] = '';
OA_output['Sponsor XXL 3'] += "<"+"a href=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ck.php?oaparams=2__bannerid=7507__zoneid=77__OXLCA=1__cb=ded5243939__oadest=http%3A%2F%2Fsquarespace.com%2F%3Fchannel%3Ddisplay%26subchannel%3Dsmashing%26source%3Dus%26campaign%3Ddisplay_ad%26subcampaign%3Dtechnology\' target=\'_blank\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/ai.php?filename=405x125-4_(3).jpg&contenttype=jpeg\' width=\'410\' height=\'125\' alt=\'\' title=\'\' border=\'0\' /><"+"/a><"+"div id=\'beacon_ded5243939\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://auslieferung.commindo-media-ressourcen.de/www/delivery/lg.php?bannerid=7507&amp;campaignid=2818&amp;zoneid=77&amp;loc=http%3A%2F%2Fwww.smashingmagazine.com%2F2010%2F01%2F28%2Fcolor-theory-for-designers-part-1-the-meaning-of-color%2F&amp;referer=http%3A%2F%2Fskylinedesign.co.ke%2Fchallenging-the-myth-of-the-color-green%2F&amp;cb=ded5243939\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['Sponsor XXL 4'] = '';

OA_output['Sponsor XXL 5'] = '';

